// Package v1alpha1openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package v1alpha1openapi

import (
	"encoding/json"
	"time"
)

// Defines values for AgentDiagnosticStatusVerdict.
const (
	AgentDiagnosticStatusVerdictCorrect   AgentDiagnosticStatusVerdict = "correct"
	AgentDiagnosticStatusVerdictIncorrect AgentDiagnosticStatusVerdict = "incorrect"
	AgentDiagnosticStatusVerdictPartial   AgentDiagnosticStatusVerdict = "partial"
)

// Valid indicates whether the value is a known member of the AgentDiagnosticStatusVerdict enum.
func (e AgentDiagnosticStatusVerdict) Valid() bool {
	switch e {
	case AgentDiagnosticStatusVerdictCorrect:
		return true
	case AgentDiagnosticStatusVerdictIncorrect:
		return true
	case AgentDiagnosticStatusVerdictPartial:
		return true
	default:
		return false
	}
}

// Defines values for SetVerdictRequestVerdict.
const (
	SetVerdictRequestVerdictCorrect   SetVerdictRequestVerdict = "correct"
	SetVerdictRequestVerdictIncorrect SetVerdictRequestVerdict = "incorrect"
	SetVerdictRequestVerdictPartial   SetVerdictRequestVerdict = "partial"
)

// Valid indicates whether the value is a known member of the SetVerdictRequestVerdict enum.
func (e SetVerdictRequestVerdict) Valid() bool {
	switch e {
	case SetVerdictRequestVerdictCorrect:
		return true
	case SetVerdictRequestVerdictIncorrect:
		return true
	case SetVerdictRequestVerdictPartial:
		return true
	default:
		return false
	}
}

// Defines values for WatchEventType.
const (
	ADDED    WatchEventType = "ADDED"
	DELETED  WatchEventType = "DELETED"
	MODIFIED WatchEventType = "MODIFIED"
)

// Valid indicates whether the value is a known member of the WatchEventType enum.
func (e WatchEventType) Valid() bool {
	switch e {
	case ADDED:
		return true
	case DELETED:
		return true
	case MODIFIED:
		return true
	default:
		return false
	}
}

// AccuracySummary defines model for AccuracySummary.
type AccuracySummary struct {
	AgentIdentity string `json:"agentIdentity"`
	CorrectCount  int64  `json:"correctCount"`

	// DiagnosticAccuracy (correctCount + 0.5 * partialCount) / totalReviewed; null when totalReviewed is 0
	DiagnosticAccuracy *float64   `json:"diagnosticAccuracy,omitempty"`
	IncorrectCount     int64      `json:"incorrectCount"`
	LastUpdatedAt      *time.Time `json:"lastUpdatedAt,omitempty"`
	Name               string     `json:"name"`
	Namespace          string     `json:"namespace"`
	PartialCount       int64      `json:"partialCount"`
	TotalReviewed      int64      `json:"totalReviewed"`
}

// AccuracySummaryList Full list of DiagnosticAccuracySummary records. Pagination is intentionally omitted — there is at most one summary per agent identity, so cardinality is bounded by the number of agents.
type AccuracySummaryList struct {
	Items []AccuracySummary `json:"items"`
}

// AgentDiagnostic defines model for AgentDiagnostic.
type AgentDiagnostic struct {
	AgentIdentity string    `json:"agentIdentity"`
	CorrelationID string    `json:"correlationID"`
	CreatedAt     time.Time `json:"createdAt"`

	// Details Free-form agent-specific diagnostic data (any JSON value)
	Details        *json.RawMessage `json:"details,omitempty"`
	DiagnosticType string           `json:"diagnosticType"`

	// Name Kubernetes object name (server-generated)
	Name      string                 `json:"name"`
	Namespace string                 `json:"namespace"`
	Status    *AgentDiagnosticStatus `json:"status,omitempty"`
	Summary   string                 `json:"summary"`
}

// AgentDiagnosticList defines model for AgentDiagnosticList.
type AgentDiagnosticList struct {
	Items []AgentDiagnostic `json:"items"`

	// NextPageToken Opaque pagination token; present only when more items exist
	NextPageToken *string `json:"nextPageToken,omitempty"`
}

// AgentDiagnosticStatus defines model for AgentDiagnosticStatus.
type AgentDiagnosticStatus struct {
	ReviewedAt *time.Time `json:"reviewedAt,omitempty"`

	// ReviewedBy Set server-side from the authenticated caller identity
	ReviewedBy   *string                       `json:"reviewedBy,omitempty"`
	ReviewerNote *string                       `json:"reviewerNote,omitempty"`
	Verdict      *AgentDiagnosticStatusVerdict `json:"verdict,omitempty"`
}

// AgentDiagnosticStatusVerdict defines model for AgentDiagnosticStatus.Verdict.
type AgentDiagnosticStatusVerdict string

// CreateAgentDiagnosticRequest defines model for CreateAgentDiagnosticRequest.
type CreateAgentDiagnosticRequest struct {
	AgentIdentity string `json:"agentIdentity"`
	CorrelationID string `json:"correlationID"`

	// Details Free-form agent-specific diagnostic data (any JSON value)
	Details        *json.RawMessage `json:"details,omitempty"`
	DiagnosticType string           `json:"diagnosticType"`
	Summary        string           `json:"summary"`
}

// MessageResponse defines model for MessageResponse.
type MessageResponse struct {
	Message string `json:"message"`
}

// Problem RFC 7807 problem detail
type Problem struct {
	Detail *string `json:"detail,omitempty"`
	Status *int    `json:"status,omitempty"`
	Title  *string `json:"title,omitempty"`
	Type   *string `json:"type,omitempty"`
}

// SetVerdictRequest defines model for SetVerdictRequest.
type SetVerdictRequest struct {
	ReviewerNote *string                  `json:"reviewerNote,omitempty"`
	Verdict      SetVerdictRequestVerdict `json:"verdict"`
}

// SetVerdictRequestVerdict defines model for SetVerdictRequest.Verdict.
type SetVerdictRequestVerdict string

// SetVerdictResponse defines model for SetVerdictResponse.
type SetVerdictResponse struct {
	Message string `json:"message"`

	// Warning Present when the accuracy summary update failed and a background recompute was triggered
	Warning *string `json:"warning,omitempty"`
}

// WatchEvent A single SSE payload for a watch stream
type WatchEvent struct {
	Object AgentDiagnostic `json:"object"`
	Type   WatchEventType  `json:"type"`
}

// WatchEventType defines model for WatchEvent.Type.
type WatchEventType string

// Name defines model for name.
type Name = string

// Namespace defines model for namespace.
type Namespace = string

// BadRequest RFC 7807 problem detail
type BadRequest = Problem

// Forbidden RFC 7807 problem detail
type Forbidden = Problem

// InternalServerError RFC 7807 problem detail
type InternalServerError = Problem

// NotFound RFC 7807 problem detail
type NotFound = Problem

// Unauthorized RFC 7807 problem detail
type Unauthorized = Problem

// ListAgentDiagnosticsParams defines parameters for ListAgentDiagnostics.
type ListAgentDiagnosticsParams struct {
	// Namespace Kubernetes namespace. Defaults to "default".
	Namespace *Namespace `form:"namespace,omitempty" json:"namespace,omitempty"`

	// AgentIdentity Filter by agent identity label
	AgentIdentity *string `form:"agentIdentity,omitempty" json:"agentIdentity,omitempty"`

	// CorrelationID Filter by correlation ID label
	CorrelationID *string `form:"correlationID,omitempty" json:"correlationID,omitempty"`

	// Limit Maximum number of items to return (pagination)
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// NextPageToken Opaque continuation token from a previous list response
	NextPageToken *string `form:"nextPageToken,omitempty" json:"nextPageToken,omitempty"`

	// CreatedAfter RFC3339 timestamp; return only records created after this time. Mutually exclusive with limit/nextPageToken.
	CreatedAfter *time.Time `form:"createdAfter,omitempty" json:"createdAfter,omitempty"`

	// CreatedBefore RFC3339 timestamp; return only records created before this time. Mutually exclusive with limit/nextPageToken.
	CreatedBefore *time.Time `form:"createdBefore,omitempty" json:"createdBefore,omitempty"`
}

// CreateAgentDiagnosticParams defines parameters for CreateAgentDiagnostic.
type CreateAgentDiagnosticParams struct {
	// Namespace Kubernetes namespace. Defaults to "default".
	Namespace *Namespace `form:"namespace,omitempty" json:"namespace,omitempty"`
}

// RecomputeAccuracyParams defines parameters for RecomputeAccuracy.
type RecomputeAccuracyParams struct {
	// Namespace Kubernetes namespace. Defaults to "default".
	Namespace *Namespace `form:"namespace,omitempty" json:"namespace,omitempty"`

	// AgentIdentity Agent identity to recompute; omit to recompute all agents
	AgentIdentity *string `form:"agentIdentity,omitempty" json:"agentIdentity,omitempty"`
}

// GetAgentDiagnosticParams defines parameters for GetAgentDiagnostic.
type GetAgentDiagnosticParams struct {
	// Namespace Kubernetes namespace. Defaults to "default".
	Namespace *Namespace `form:"namespace,omitempty" json:"namespace,omitempty"`
}

// SetAgentDiagnosticVerdictParams defines parameters for SetAgentDiagnosticVerdict.
type SetAgentDiagnosticVerdictParams struct {
	// Namespace Kubernetes namespace. Defaults to "default".
	Namespace *Namespace `form:"namespace,omitempty" json:"namespace,omitempty"`
}

// WatchAgentDiagnosticParams defines parameters for WatchAgentDiagnostic.
type WatchAgentDiagnosticParams struct {
	// Namespace Kubernetes namespace. Defaults to "default".
	Namespace *Namespace `form:"namespace,omitempty" json:"namespace,omitempty"`
}

// ListAccuracySummariesParams defines parameters for ListAccuracySummaries.
type ListAccuracySummariesParams struct {
	// Namespace Kubernetes namespace. Defaults to "default".
	Namespace *Namespace `form:"namespace,omitempty" json:"namespace,omitempty"`
}

// CreateAgentDiagnosticJSONRequestBody defines body for CreateAgentDiagnostic for application/json ContentType.
type CreateAgentDiagnosticJSONRequestBody = CreateAgentDiagnosticRequest

// SetAgentDiagnosticVerdictJSONRequestBody defines body for SetAgentDiagnosticVerdict for application/json ContentType.
type SetAgentDiagnosticVerdictJSONRequestBody = SetVerdictRequest
