apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: manager
        args:
        - --leader-elect
        - --health-probe-bind-address=:8081
        - --gc-enabled=false
        - --ops-lock-duration=15s
        - --ops-lock-wait-timeout=20s
