# This rule is not used by the project aip-k8s itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to governance.aip.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: aip-k8s
    app.kubernetes.io/managed-by: kustomize
  name: agentdiagnostic-viewer-role
rules:
- apiGroups:
  - governance.aip.io
  resources:
  - agentdiagnostics
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - governance.aip.io
  resources:
  - agentdiagnostics/status
  verbs:
  - get
