apiVersion: governance.aip.io/v1alpha1
kind: DiagnosticAccuracySummary
metadata:
  labels:
    app.kubernetes.io/name: aip-k8s
    app.kubernetes.io/managed-by: kustomize
  name: diagnosticaccuracysummary-sample
spec:
  agentIdentity: k8s-debug-agent
