## Append samples of your project ##
resources:
- governance_v1alpha1_agentrequest.yaml
- governance_v1alpha1_safetypolicy.yaml
- governance_v1alpha1_auditrecord.yaml
- governance_v1alpha1_agentdiagnostic.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
