/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

import (
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// AgentDiagnosticSpec defines what the agent observed.
// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="AgentDiagnostic spec is immutable after creation"
type AgentDiagnosticSpec struct {
	// AgentIdentity is the identity of the agent that recorded this diagnostic.
	// Must match the agentIdentity the agent uses in subsequent AgentRequests.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinLength=1
	AgentIdentity string `json:"agentIdentity"`

	// DiagnosticType categorizes the observation.
	// Recommended values: observation, diagnosis, signal, escalation.
	// Open string — adopters may define domain-specific types.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinLength=1
	DiagnosticType string `json:"diagnosticType"`

	// CorrelationID is a UUID generated by the agent before acting.
	// Set as a label (aip.io/correlationID) on this record and on any
	// subsequent AgentRequest to enable cross-resource querying.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinLength=1
	CorrelationID string `json:"correlationID"`

	// Summary is a human-readable description of what the agent observed.
	// Required. Consumed by dashboards and audit tooling.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MaxLength=1024
	Summary string `json:"summary"`

	// Details contains agent-specific diagnostic data in open JSON.
	// Optional. Examples: confidence scores, evidence sources, alternatives considered.
	// +optional
	Details *apiextensionsv1.JSON `json:"details,omitempty"`
}

// AgentDiagnostic is the Schema for agent-originated diagnostic records.
// +kubebuilder:object:root=true
// +kubebuilder:resource:scope=Namespaced
// +kubebuilder:printcolumn:name="Agent",type=string,JSONPath=`.spec.agentIdentity`
// +kubebuilder:printcolumn:name="Type",type=string,JSONPath=`.spec.diagnosticType`
// +kubebuilder:printcolumn:name="Summary",type=string,JSONPath=`.spec.summary`
// +kubebuilder:printcolumn:name="Age",type=date,JSONPath=`.metadata.creationTimestamp`
type AgentDiagnostic struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec AgentDiagnosticSpec `json:"spec,omitempty"`
}

// +kubebuilder:object:root=true

// AgentDiagnosticList contains a list of AgentDiagnostic
type AgentDiagnosticList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AgentDiagnostic `json:"items"`
}

func init() {
	SchemeBuilder.Register(&AgentDiagnostic{}, &AgentDiagnosticList{})
}
