//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AffectedTarget) DeepCopyInto(out *AffectedTarget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AffectedTarget.
func (in *AffectedTarget) DeepCopy() *AffectedTarget {
	if in == nil {
		return nil
	}
	out := new(AffectedTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentDiagnostic) DeepCopyInto(out *AgentDiagnostic) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentDiagnostic.
func (in *AgentDiagnostic) DeepCopy() *AgentDiagnostic {
	if in == nil {
		return nil
	}
	out := new(AgentDiagnostic)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentDiagnostic) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentDiagnosticList) DeepCopyInto(out *AgentDiagnosticList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentDiagnostic, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentDiagnosticList.
func (in *AgentDiagnosticList) DeepCopy() *AgentDiagnosticList {
	if in == nil {
		return nil
	}
	out := new(AgentDiagnosticList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentDiagnosticList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentDiagnosticSpec) DeepCopyInto(out *AgentDiagnosticSpec) {
	*out = *in
	if in.Details != nil {
		in, out := &in.Details, &out.Details
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentDiagnosticSpec.
func (in *AgentDiagnosticSpec) DeepCopy() *AgentDiagnosticSpec {
	if in == nil {
		return nil
	}
	out := new(AgentDiagnosticSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentDiagnosticStatus) DeepCopyInto(out *AgentDiagnosticStatus) {
	*out = *in
	if in.ReviewedAt != nil {
		in, out := &in.ReviewedAt, &out.ReviewedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentDiagnosticStatus.
func (in *AgentDiagnosticStatus) DeepCopy() *AgentDiagnosticStatus {
	if in == nil {
		return nil
	}
	out := new(AgentDiagnosticStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRequest) DeepCopyInto(out *AgentRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRequest.
func (in *AgentRequest) DeepCopy() *AgentRequest {
	if in == nil {
		return nil
	}
	out := new(AgentRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRequestList) DeepCopyInto(out *AgentRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRequestList.
func (in *AgentRequestList) DeepCopy() *AgentRequestList {
	if in == nil {
		return nil
	}
	out := new(AgentRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRequestSpec) DeepCopyInto(out *AgentRequestSpec) {
	*out = *in
	in.Target.DeepCopyInto(&out.Target)
	if in.IntentPlanRef != nil {
		in, out := &in.IntentPlanRef, &out.IntentPlanRef
		*out = new(string)
		**out = **in
	}
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(int32)
		**out = **in
	}
	if in.CascadeModel != nil {
		in, out := &in.CascadeModel, &out.CascadeModel
		*out = new(CascadeModel)
		(*in).DeepCopyInto(*out)
	}
	if in.ReasoningTrace != nil {
		in, out := &in.ReasoningTrace, &out.ReasoningTrace
		*out = new(ReasoningTrace)
		(*in).DeepCopyInto(*out)
	}
	if in.Interruptibility != nil {
		in, out := &in.Interruptibility, &out.Interruptibility
		*out = new(bool)
		**out = **in
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.ExecutionMode != nil {
		in, out := &in.ExecutionMode, &out.ExecutionMode
		*out = new(string)
		**out = **in
	}
	if in.ScopeBounds != nil {
		in, out := &in.ScopeBounds, &out.ScopeBounds
		*out = new(ScopeBounds)
		(*in).DeepCopyInto(*out)
	}
	if in.HumanApproval != nil {
		in, out := &in.HumanApproval, &out.HumanApproval
		*out = new(HumanApproval)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRequestSpec.
func (in *AgentRequestSpec) DeepCopy() *AgentRequestSpec {
	if in == nil {
		return nil
	}
	out := new(AgentRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRequestStatus) DeepCopyInto(out *AgentRequestStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Denial != nil {
		in, out := &in.Denial, &out.Denial
		*out = new(DenialResponse)
		(*in).DeepCopyInto(*out)
	}
	if in.ControlPlaneVerification != nil {
		in, out := &in.ControlPlaneVerification, &out.ControlPlaneVerification
		*out = new(ControlPlaneVerification)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRequestStatus.
func (in *AgentRequestStatus) DeepCopy() *AgentRequestStatus {
	if in == nil {
		return nil
	}
	out := new(AgentRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditLockStatus) DeepCopyInto(out *AuditLockStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditLockStatus.
func (in *AuditLockStatus) DeepCopy() *AuditLockStatus {
	if in == nil {
		return nil
	}
	out := new(AuditLockStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditPolicyEvaluation) DeepCopyInto(out *AuditPolicyEvaluation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditPolicyEvaluation.
func (in *AuditPolicyEvaluation) DeepCopy() *AuditPolicyEvaluation {
	if in == nil {
		return nil
	}
	out := new(AuditPolicyEvaluation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditRecord) DeepCopyInto(out *AuditRecord) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditRecord.
func (in *AuditRecord) DeepCopy() *AuditRecord {
	if in == nil {
		return nil
	}
	out := new(AuditRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AuditRecord) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditRecordList) DeepCopyInto(out *AuditRecordList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AuditRecord, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditRecordList.
func (in *AuditRecordList) DeepCopy() *AuditRecordList {
	if in == nil {
		return nil
	}
	out := new(AuditRecordList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AuditRecordList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditRecordSpec) DeepCopyInto(out *AuditRecordSpec) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
	if in.PhaseTransition != nil {
		in, out := &in.PhaseTransition, &out.PhaseTransition
		*out = new(PhaseTransition)
		**out = **in
	}
	if in.PolicyEvaluations != nil {
		in, out := &in.PolicyEvaluations, &out.PolicyEvaluations
		*out = make([]AuditPolicyEvaluation, len(*in))
		copy(*out, *in)
	}
	if in.LockStatus != nil {
		in, out := &in.LockStatus, &out.LockStatus
		*out = new(AuditLockStatus)
		**out = **in
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Details != nil {
		in, out := &in.Details, &out.Details
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditRecordSpec.
func (in *AuditRecordSpec) DeepCopy() *AuditRecordSpec {
	if in == nil {
		return nil
	}
	out := new(AuditRecordSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditRecordStatus) DeepCopyInto(out *AuditRecordStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditRecordStatus.
func (in *AuditRecordStatus) DeepCopy() *AuditRecordStatus {
	if in == nil {
		return nil
	}
	out := new(AuditRecordStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CascadeModel) DeepCopyInto(out *CascadeModel) {
	*out = *in
	if in.AffectedTargets != nil {
		in, out := &in.AffectedTargets, &out.AffectedTargets
		*out = make([]AffectedTarget, len(*in))
		copy(*out, *in)
	}
	if in.ModelSourceTrust != nil {
		in, out := &in.ModelSourceTrust, &out.ModelSourceTrust
		*out = new(string)
		**out = **in
	}
	if in.ModelSourceID != nil {
		in, out := &in.ModelSourceID, &out.ModelSourceID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CascadeModel.
func (in *CascadeModel) DeepCopy() *CascadeModel {
	if in == nil {
		return nil
	}
	out := new(CascadeModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneVerification) DeepCopyInto(out *ControlPlaneVerification) {
	*out = *in
	if in.DownstreamServices != nil {
		in, out := &in.DownstreamServices, &out.DownstreamServices
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.FetchedAt.DeepCopyInto(&out.FetchedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneVerification.
func (in *ControlPlaneVerification) DeepCopy() *ControlPlaneVerification {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneVerification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DenialResponse) DeepCopyInto(out *DenialResponse) {
	*out = *in
	if in.PolicyResults != nil {
		in, out := &in.PolicyResults, &out.PolicyResults
		*out = make([]PolicyResult, len(*in))
		copy(*out, *in)
	}
	if in.RetryAfterSeconds != nil {
		in, out := &in.RetryAfterSeconds, &out.RetryAfterSeconds
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DenialResponse.
func (in *DenialResponse) DeepCopy() *DenialResponse {
	if in == nil {
		return nil
	}
	out := new(DenialResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiagnosticAccuracySummary) DeepCopyInto(out *DiagnosticAccuracySummary) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiagnosticAccuracySummary.
func (in *DiagnosticAccuracySummary) DeepCopy() *DiagnosticAccuracySummary {
	if in == nil {
		return nil
	}
	out := new(DiagnosticAccuracySummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DiagnosticAccuracySummary) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiagnosticAccuracySummaryList) DeepCopyInto(out *DiagnosticAccuracySummaryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DiagnosticAccuracySummary, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiagnosticAccuracySummaryList.
func (in *DiagnosticAccuracySummaryList) DeepCopy() *DiagnosticAccuracySummaryList {
	if in == nil {
		return nil
	}
	out := new(DiagnosticAccuracySummaryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DiagnosticAccuracySummaryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiagnosticAccuracySummarySpec) DeepCopyInto(out *DiagnosticAccuracySummarySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiagnosticAccuracySummarySpec.
func (in *DiagnosticAccuracySummarySpec) DeepCopy() *DiagnosticAccuracySummarySpec {
	if in == nil {
		return nil
	}
	out := new(DiagnosticAccuracySummarySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiagnosticAccuracySummaryStatus) DeepCopyInto(out *DiagnosticAccuracySummaryStatus) {
	*out = *in
	if in.DiagnosticAccuracy != nil {
		in, out := &in.DiagnosticAccuracy, &out.DiagnosticAccuracy
		*out = new(float64)
		**out = **in
	}
	if in.LastUpdatedAt != nil {
		in, out := &in.LastUpdatedAt, &out.LastUpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiagnosticAccuracySummaryStatus.
func (in *DiagnosticAccuracySummaryStatus) DeepCopy() *DiagnosticAccuracySummaryStatus {
	if in == nil {
		return nil
	}
	out := new(DiagnosticAccuracySummaryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumanApproval) DeepCopyInto(out *HumanApproval) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumanApproval.
func (in *HumanApproval) DeepCopy() *HumanApproval {
	if in == nil {
		return nil
	}
	out := new(HumanApproval)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PhaseTransition) DeepCopyInto(out *PhaseTransition) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PhaseTransition.
func (in *PhaseTransition) DeepCopy() *PhaseTransition {
	if in == nil {
		return nil
	}
	out := new(PhaseTransition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyResult) DeepCopyInto(out *PolicyResult) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyResult.
func (in *PolicyResult) DeepCopy() *PolicyResult {
	if in == nil {
		return nil
	}
	out := new(PolicyResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReasoningTrace) DeepCopyInto(out *ReasoningTrace) {
	*out = *in
	if in.ConfidenceScore != nil {
		in, out := &in.ConfidenceScore, &out.ConfidenceScore
		*out = new(float64)
		**out = **in
	}
	if in.ComponentConfidence != nil {
		in, out := &in.ComponentConfidence, &out.ComponentConfidence
		*out = make(map[string]float64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.CalibrationEvidence != nil {
		in, out := &in.CalibrationEvidence, &out.CalibrationEvidence
		*out = new(string)
		**out = **in
	}
	if in.TraceReference != nil {
		in, out := &in.TraceReference, &out.TraceReference
		*out = new(string)
		**out = **in
	}
	if in.Alternatives != nil {
		in, out := &in.Alternatives, &out.Alternatives
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReasoningTrace.
func (in *ReasoningTrace) DeepCopy() *ReasoningTrace {
	if in == nil {
		return nil
	}
	out := new(ReasoningTrace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Rule) DeepCopyInto(out *Rule) {
	*out = *in
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Rule.
func (in *Rule) DeepCopy() *Rule {
	if in == nil {
		return nil
	}
	out := new(Rule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SafetyPolicy) DeepCopyInto(out *SafetyPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SafetyPolicy.
func (in *SafetyPolicy) DeepCopy() *SafetyPolicy {
	if in == nil {
		return nil
	}
	out := new(SafetyPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SafetyPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SafetyPolicyList) DeepCopyInto(out *SafetyPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SafetyPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SafetyPolicyList.
func (in *SafetyPolicyList) DeepCopy() *SafetyPolicyList {
	if in == nil {
		return nil
	}
	out := new(SafetyPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SafetyPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SafetyPolicySpec) DeepCopyInto(out *SafetyPolicySpec) {
	*out = *in
	in.TargetSelector.DeepCopyInto(&out.TargetSelector)
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]Rule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FailureMode != nil {
		in, out := &in.FailureMode, &out.FailureMode
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SafetyPolicySpec.
func (in *SafetyPolicySpec) DeepCopy() *SafetyPolicySpec {
	if in == nil {
		return nil
	}
	out := new(SafetyPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SafetyPolicyStatus) DeepCopyInto(out *SafetyPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SafetyPolicyStatus.
func (in *SafetyPolicyStatus) DeepCopy() *SafetyPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(SafetyPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScopeBounds) DeepCopyInto(out *ScopeBounds) {
	*out = *in
	if in.PermittedActions != nil {
		in, out := &in.PermittedActions, &out.PermittedActions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PermittedTargetPatterns != nil {
		in, out := &in.PermittedTargetPatterns, &out.PermittedTargetPatterns
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScopeBounds.
func (in *ScopeBounds) DeepCopy() *ScopeBounds {
	if in == nil {
		return nil
	}
	out := new(ScopeBounds)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Target) DeepCopyInto(out *Target) {
	*out = *in
	if in.ResourceType != nil {
		in, out := &in.ResourceType, &out.ResourceType
		*out = new(string)
		**out = **in
	}
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Target.
func (in *Target) DeepCopy() *Target {
	if in == nil {
		return nil
	}
	out := new(Target)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetSelector) DeepCopyInto(out *TargetSelector) {
	*out = *in
	if in.MatchAttributes != nil {
		in, out := &in.MatchAttributes, &out.MatchAttributes
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.MatchResourceTypes != nil {
		in, out := &in.MatchResourceTypes, &out.MatchResourceTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MatchActions != nil {
		in, out := &in.MatchActions, &out.MatchActions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetSelector.
func (in *TargetSelector) DeepCopy() *TargetSelector {
	if in == nil {
		return nil
	}
	out := new(TargetSelector)
	in.DeepCopyInto(out)
	return out
}
