#!/usr/bin/env bash
# check-helm-rbac.sh — verify that every governance.aip.io resource in
# config/rbac/role.yaml is also present in the Helm chart ClusterRole.
#
# Detects RBAC drift: controller markers regenerated via 'make manifests' but
# the Helm chart ClusterRole was not manually updated to match.
#
# Exits 1 if any resource is missing from the Helm chart; lists every gap.
# Run with `make helm-rbac-check`.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
KUSTOMIZE_ROLE="$REPO_ROOT/config/rbac/role.yaml"
HELM_RBAC="$REPO_ROOT/charts/aip-k8s/templates/controller/rbac.yaml"
API_GROUP="governance.aip.io"

fail=0

if [ ! -f "$KUSTOMIZE_ROLE" ]; then
    echo "ERROR: $KUSTOMIZE_ROLE does not exist — run 'make manifests' first." >&2
    exit 1
fi

if [ ! -f "$HELM_RBAC" ]; then
    echo "ERROR: $HELM_RBAC does not exist." >&2
    exit 1
fi

# Extract resource names listed under governance.aip.io rules in config/rbac/role.yaml.
# Parses each apiGroups block; collects resource entries until the next block or EOF.
# A resource line looks like:  - resourcename   (possibly with /subresource suffix)
# Written without
# mapfile/process-substitution to remain compatible with bash 3.x (macOS default).
canonical_resources_file="$(mktemp)"
trap 'rm -f "$canonical_resources_file"' EXIT

awk '
    /apiGroups:/ { in_gov=0 }
    /- '"$API_GROUP"'/ { in_gov=1; next }
    in_gov && /^  resources:/ { collecting=1; next }
    in_gov && collecting && /^  - / {
        sub(/^  - /, ""); print
    }
    in_gov && collecting && !/^  - / && !/^$/ { collecting=0 }
' "$KUSTOMIZE_ROLE" > "$canonical_resources_file"

if [ ! -s "$canonical_resources_file" ]; then
    echo "ERROR: no $API_GROUP resources found in $KUSTOMIZE_ROLE." >&2
    echo "  Is 'make manifests' up to date?" >&2
    exit 1
fi

# Check each canonical resource against the Helm chart ClusterRole.
missing_file="$(mktemp)"
trap 'rm -f "$canonical_resources_file" "$missing_file"' EXIT

while IFS= read -r resource; do
    # Anchor on end-of-line so "agentdiagnostics" does not match "agentdiagnostics/status".
    if ! grep -qE "^[[:space:]]*- ${resource}$" "$HELM_RBAC"; then
        echo "$resource" >> "$missing_file"
    fi
done < "$canonical_resources_file"

if [ -s "$missing_file" ]; then
    echo "RBAC DRIFT: the following $API_GROUP resources are in $KUSTOMIZE_ROLE"
    echo "  but missing from $HELM_RBAC:"
    while IFS= read -r r; do
        echo "    - $r"
    done < "$missing_file"
    echo ""
    echo "Update the ClusterRole in $HELM_RBAC to include the missing entries."
    echo "(Canonical source: $KUSTOMIZE_ROLE — regenerated by 'make manifests')"
    fail=1
fi

if [ "$fail" -ne 0 ]; then
    exit 1
fi

echo "Helm chart RBAC is in sync with $KUSTOMIZE_ROLE."
