// scripts/generate-api-docs.go
// Auto-generates the Gateway API endpoints table in docs/api-reference.md
// from HandleFunc registrations in cmd/gateway/main.go.
//
//go:build ignore
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

var handlerDescriptions = map[string]string{
	"WhoAmI":                      "Return current authenticated identity",
	"ListAgentRequests":           "List AgentRequests",
	"CreateAgentRequest":          "Submit an AgentRequest",
	"GetAgentRequest":             "Get an AgentRequest by name",
	"WatchAgentRequest":           "Watch an AgentRequest via SSE",
	"ExecutingAgentRequest":       "Signal agent started executing",
	"CompletedAgentRequest":       "Signal agent completed the action",
	"ApproveAgentRequest":         "Approve an AgentRequest",
	"DenyAgentRequest":            "Deny an AgentRequest",
	"VerdictAgentRequest":         "Submit a verdict (correct/incorrect)",
	"ListAuditRecords":            "List AuditRecords",
	"RecomputeAccuracy":           "Trigger accuracy recomputation",
	"ListAccuracySummaries":       "List DiagnosticAccuracySummaries",
	"ListAgentTrustProfiles":      "List AgentTrustProfiles",
	"GetAgentTrustProfile":        "Get an AgentTrustProfile by name",
	"CreateGovernedResource":      "Create a GovernedResource",
	"ListGovernedResources":       "List GovernedResources",
	"GetGovernedResource":         "Get a GovernedResource by name",
	"ReplaceGovernedResource":     "Replace a GovernedResource",
	"DeleteGovernedResource":      "Delete a GovernedResource",
	"CreateSafetyPolicy":          "Create a SafetyPolicy",
	"ListSafetyPolicies":          "List SafetyPolicies",
	"GetSafetyPolicy":             "Get a SafetyPolicy by name",
	"ReplaceSafetyPolicy":         "Replace a SafetyPolicy",
	"DeleteSafetyPolicy":          "Delete a SafetyPolicy",
	"CreateAgentGraduationPolicy": "Create an AgentGraduationPolicy",
	"ListAgentGraduationPolicies": "List AgentGraduationPolicies",
	"GetAgentGraduationPolicy":    "Get an AgentGraduationPolicy by name",
	"ReplaceAgentGraduationPolicy": "Replace an AgentGraduationPolicy",
	"DeleteAgentGraduationPolicy": "Delete an AgentGraduationPolicy",
}

type route struct {
	Method  string
	Path    string
	Handler string
}

func projectRoot() string {
	// When running via `go run`, the binary is in a temp directory.
	// Use the working directory or walk up from the script location.
	if dir := os.Getenv("PROJECT_ROOT"); dir != "" {
		return dir
	}
	exeDir := filepath.Dir(os.Args[0])
	if strings.Contains(exeDir, "go-build") || strings.Contains(exeDir, "/tmp/") {
		wd, err := os.Getwd()
		if err == nil {
			return wd
		}
	}
	root, err := filepath.Abs(filepath.Join(exeDir, ".."))
	if err != nil {
		fmt.Fprintf(os.Stderr, "ERROR: finding project root: %v\n", err)
		os.Exit(1)
	}
	return root
}

func main() {
	projectRoot := projectRoot()
	gatewayMain := filepath.Join(projectRoot, "cmd", "gateway", "main.go")
	apiDoc := filepath.Join(projectRoot, "docs", "api-reference.md")

	routes, err := extractRoutes(gatewayMain)
	if err != nil {
		fmt.Fprintf(os.Stderr, "ERROR: extracting routes: %v\n", err)
		os.Exit(1)
	}

	table := generateTable(routes)
	if err := replaceTable(apiDoc, table); err != nil {
		fmt.Fprintf(os.Stderr, "ERROR: replacing table: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated API endpoints table in %s\n", apiDoc)
}

func extractRoutes(path string) ([]route, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}

	var routes []route
	re := regexp.MustCompile(`mux\.HandleFunc\("([^"]+)",\s*(?:server\.)?handle([A-Za-z]+)`)
	for _, match := range re.FindAllSubmatch(data, -1) {
		routeStr := string(match[1])
		handler := string(match[2])
		parts := strings.SplitN(routeStr, " ", 2)
		if len(parts) == 2 {
			routes = append(routes, route{Method: parts[0], Path: parts[1], Handler: handler})
		}
	}

	sort.Slice(routes, func(i, j int) bool {
		return routes[i].Handler < routes[j].Handler
	})

	return routes, nil
}

func generateTable(routes []route) string {
	var b strings.Builder
	b.WriteString("<!-- BEGIN_API_TABLE -->\n")
	b.WriteString("<!-- Auto-generated by scripts/generate-api-docs.go -- do not edit manually -->\n")
	b.WriteString("| Method | Path | Description |\n")
	b.WriteString("|--------|------|-------------|\n")

	for _, r := range routes {
		desc, ok := handlerDescriptions[r.Handler]
		if !ok {
			continue
		}
		fmt.Fprintf(&b, "| `%s` | `%s` | %s |\n", r.Method, r.Path, desc)
	}

	b.WriteString("<!-- END_API_TABLE -->")
	return b.String()
}

func replaceTable(docPath, newTable string) error {
	content, err := os.ReadFile(docPath)
	if err != nil {
		return err
	}

	startMarker := "<!-- BEGIN_API_TABLE -->"
	endMarker := "<!-- END_API_TABLE -->"

	startIdx := strings.Index(string(content), startMarker)
	if startIdx == -1 {
		return fmt.Errorf("BEGIN_API_TABLE marker not found in %s", docPath)
	}

	endIdx := strings.Index(string(content[startIdx:]), endMarker)
	if endIdx == -1 {
		return fmt.Errorf("END_API_TABLE marker not found in %s", docPath)
	}
	endIdx += startIdx + len(endMarker)

	result := string(content[:startIdx]) + newTable + string(content[endIdx:])
	return os.WriteFile(docPath, []byte(result), 0644)
}
