name: E2E Tests

on:
  push:
    branches:
      - main
  pull_request:

env:
  KIND_VERSION: v0.31.0
  CERT_MANAGER_VERSION: v1.19.4

jobs:
  test-e2e:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/${{ env.KIND_VERSION }}/kind-linux-$(go env GOARCH)
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Verify kind installation
        run: kind version

      - name: Create Kind cluster
        run: make setup-test-e2e

      - name: Install cert-manager
        run: |
          kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/${{ env.CERT_MANAGER_VERSION }}/cert-manager.yaml
          kubectl wait deployment/cert-manager-cainjector \
            --for=condition=Available \
            --namespace=cert-manager \
            --timeout=5m
          kubectl wait deployment/cert-manager \
            --for=condition=Available \
            --namespace=cert-manager \
            --timeout=5m
          kubectl wait deployment/cert-manager-webhook \
            --for=condition=Available \
            --namespace=cert-manager \
            --timeout=5m

      - name: Running Test e2e
        run: |
          go mod tidy
          make test-e2e
        env:
          CERT_MANAGER_INSTALL_SKIP: "true"
